// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-sxcbS7C4S8md3dwtj9hzKGxNkzvfvj0',
    appId: '1:902642303689:web:4a9f04662376fabbe24318',
    messagingSenderId: '902642303689',
    projectId: 'instachat-72c71',
    authDomain: 'instachat-72c71.firebaseapp.com',
    databaseURL: 'https://instachat-72c71-default-rtdb.firebaseio.com',
    storageBucket: 'instachat-72c71.appspot.com',
    measurementId: 'G-Q56B6KHT90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaYBhxZ-bLZza-CcA5m91ZL5xgZo6bJI0',
    appId: '1:902642303689:android:b2c43bf7aa0740a0e24318',
    messagingSenderId: '902642303689',
    projectId: 'instachat-72c71',
    databaseURL: 'https://instachat-72c71-default-rtdb.firebaseio.com',
    storageBucket: 'instachat-72c71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bmF1ddrx78ruN_sWJgVWxh5do5yG8i8',
    appId: '1:902642303689:ios:ffcb534f568458dee24318',
    messagingSenderId: '902642303689',
    projectId: 'instachat-72c71',
    databaseURL: 'https://instachat-72c71-default-rtdb.firebaseio.com',
    storageBucket: 'instachat-72c71.appspot.com',
    iosClientId: '902642303689-ebelrarjpduecj68au1tclc6blcrmekd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1bmF1ddrx78ruN_sWJgVWxh5do5yG8i8',
    appId: '1:902642303689:ios:ffcb534f568458dee24318',
    messagingSenderId: '902642303689',
    projectId: 'instachat-72c71',
    databaseURL: 'https://instachat-72c71-default-rtdb.firebaseio.com',
    storageBucket: 'instachat-72c71.appspot.com',
    iosClientId: '902642303689-ebelrarjpduecj68au1tclc6blcrmekd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKQLeNPG-Md0hu4x0BSoN5vWpHR-7QIiY',
    appId: '1:902642303689:web:59f7469d85e900a3e24318',
    messagingSenderId: '902642303689',
    projectId: 'instachat-72c71',
    authDomain: 'instachat-72c71.firebaseapp.com',
    databaseURL: 'https://instachat-72c71-default-rtdb.firebaseio.com',
    storageBucket: 'instachat-72c71.appspot.com',
    measurementId: 'G-FX49N3Q98B',
  );
}
